#!/bin/sh
git push origin
ssh www@stricteq.com <<'SCRIPT'
cd /var/www/stricteq/
old_hash="$(shasum package-lock.json)"
git fetch origin
git reset --hard origin/main
new_hash="$(shasum package-lock.json)"
[ "$old_hash" != "$new_hash" ] && npm ci
systemctl --user restart stricteq
SCRIPT
